malybar/malybar/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    url(r'^', include('pizza.urls', namespace='pizza')),
    url(r'^pizza/', include('pizza.urls', namespace='pizza')),
    url(r'^konta/', include('registration.backends.simple.urls')),
    url(r'^admin/', admin.site.urls),
]

malybar/pizza/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views  # import widoków aplikacji
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from .models import Pizza
from .models import Skladnik

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^kontakt$', views.kontakt, name='kontakt'),
    url(r'^lista/', login_required(ListView.as_view(model=Pizza)),
    name='lista'),
    url(r'^listas/', login_required(ListView.as_view(model=Skladnik)),
    name='listas'),
    url(r'^dodaj/$', views.PizzaCreate.as_view(), name='dodaj'),
    url(r'^edytuj/(?P<pk>\d+)/', views.PizzaUpdate.as_view(), name='edytuj'),
    url(r'^usun/(?P<pk>\d+)/', views.PizzaDelete.as_view(), name='usun'),
    url(r'^info/(?P<pk>\d+)/', views.PizzaDetail.as_view(), name='info'),

]

malybar/pizza/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


class Pizza(models.Model):
    LARGE = 'L'
    MEDIUM = 'M'
    SMALL = 'S'
    ROZMIARY = (
        (LARGE, 'duża'),
        (MEDIUM, 'średnia'),
        (SMALL, 'mała'),
    )
    nazwa = models.CharField(verbose_name='Pizza', max_length=30)
    opis = models.TextField(blank=True, help_text='Opis Pizzy')
    rozmiar = models.CharField(max_length=1, choices=ROZMIARY, default=LARGE)
    cena = models.DecimalField(max_digits=5, decimal_places=2)
    data = models.DateField('dodano', auto_now_add=True)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)

    def __unicode__(self):
        return u'%s' % (self.nazwa)

    class Meta:
        verbose_name_plural = 'pizze'


class Skladnik(models.Model):
    pizza = models.ForeignKey(Pizza, related_name='skladniki')
    nazwa = models.CharField(verbose_name=u"składnik", max_length=30)
    jarski = models.BooleanField(
        default=False,
        verbose_name=u"jarski?",
        help_text=u"Zaznacz, jeżeli składnik jest odpowiedni dla"
        u" wegetarian")

    def __unicode__(self):
        return u'%s' % (self.nazwa)

    def czy_jarski(self):
        if self.jarski:
            return 'jarski'
        return 'niejarski'

    class Meta:
        verbose_name_plural = u'Składniki'

malybar/pizza/forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm, Textarea
from . import models
from django.forms.models import inlineformset_factory


class PizzaForm(ModelForm):

    class Meta:
        model = models.Pizza
        exclude = ('data', 'autor')
        widgets = {'opis': Textarea(attrs={'rows': 2, 'cols': 80})}


SkladnikiFormSet = inlineformset_factory(
    parent_model=models.Pizza,
    model=models.Skladnik,
    max_num=6,
    min_num=1,
    validate_max=True,
    validate_min=True,
    extra=2,
    fields=('nazwa', 'jarski')
)

malybar/pizza/views.py
# -*- coding: utf-8 -*-

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from . import models
from . import forms
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render

#test3

def index(request):
    """Strona główna"""
    kontekst = {'komunikat': 'Witaj w aplikacji Pizza!'}
    return render(request, 'pizza/index.html', kontekst)


def kontakt(request):
    """kontakt"""
    kontekst = {'kontakt': 'budynek A0'}
    return render(request, 'pizza/kontakt.html', kontekst)


@method_decorator(login_required, 'dispatch')
class PizzaCreate(CreateView):
    """Widok dodawania pizzy i skladników."""

    model = models.Pizza
    form_class = forms.PizzaForm
    success_url = reverse_lazy('pizza:lista')  # '/pizza/lista'

    def get_context_data(self, **kwargs):
        context = super(PizzaCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            context['skladniki'] = forms.SkladnikiFormSet(self.request.POST)
        else:
            context['skladniki'] = forms.SkladnikiFormSet()
            context['imie'] = 'Przemek'
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        skladniki = forms.SkladnikiFormSet(self.request.POST)
        if form.is_valid() and skladniki.is_valid():
            return self.form_valid(form, skladniki)
        else:
            return self.form_invalid(form, skladniki)

    def form_valid(self, form, skladniki):
        form.instance.autor = self.request.user
        self.object = form.save()
        skladniki.instance = self.object
        skladniki.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, skladniki):
        return self.render_to_response(
            self.get_context_data(form=form, skladniki=skladniki)
        )


@method_decorator(login_required, 'dispatch')
class PizzaUpdate(UpdateView):
    """Widok aktualizuacji"""

    model = models.Pizza
    form_class = forms.PizzaForm
    success_url = reverse_lazy('pizza:lista')  # '/pizza/lista'

    def get_context_data(self, **kwargs):
        context = super(PizzaUpdate, self).get_context_data(**kwargs)
        if self.request.POST:
            context['skladniki'] = forms.SkladnikiFormSet(
                self.request.POST,
                instance=self.object)
        else:
            context['skladniki'] = forms.SkladnikiFormSet(instance=self.object)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        skladniki = forms.SkladnikiFormSet(
            self.request.POST,
            instance=self.object)
        if form.is_valid() and skladniki.is_valid():
            return self.form_valid(form, skladniki)
        else:
            return self.form_invalid(form, skladniki)

    def form_valid(self, form, skladniki):
        form.instance.autor = self.request.user
        self.object = form.save()
        skladniki.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, skladniki):
        return self.render_to_response(
            self.get_context_data(form=form, skladniki=skladniki)
        )


@method_decorator(login_required, 'dispatch')
class PizzaDelete(DeleteView):
    model = models.Pizza
    success_url = reverse_lazy('pizza:lista')  # '/pizza/lista'

    def get_context_data(self, **kwargs):
        context = super(PizzaDelete, self).get_context_data(**kwargs)
        skladniki = models.Skladnik.objects.filter(pizza=self.object)
        context['skladniki'] = skladniki
        return context

@method_decorator(login_required, 'dispatch')
class PizzaDetail(DetailView):
    model = models.Pizza

    def get_context_data(self, **kwargs):
        context = super(PizzaDetail, self).get_context_data(**kwargs)
        skladniki = models.Skladnik.objects.filter(pizza=self.object)
        context['skladniki'] = skladniki
        return context

malybar/pizza/templates/pizza/base.html
{% load static %}<!DOCTYPE html>
<html lang="pl">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>{% block tytul_head %}Ciasto + składniki = Pizza{% endblock %}</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <link href="{% static 'pizza/css/pizza.css' %}" rel="stylesheet">
</head>
<body>

<!-- Nawigacja -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Przełącz nawigację</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'pizza:index' %}">
        <img src="{% static 'pizza/images/pizza.jpg' %}" class="img-thumbnail img-logo">
      </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        {% if not user.is_authenticated %}
        <li><a href="{% url 'auth_login' %}">Zaloguj</a></li>
        <li><a href="{% url 'registration_register' %}">Utwórz konto</a></li>
        {% else %}
        <li><a href="{% url 'pizza:dodaj' %}">Dodaj pizzę</a></li>
        <li><a href="{% url 'pizza:lista' %}">Lista pizz</a></li>
        <li><a href="{% url 'auth_logout' %}">Wyloguj: {{ user.username }}</a></li>
        {% endif %}
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<!-- Treść główna -->
<div class="container">

  <div class="row">

    <div class="col-sm-8">

      <noscript><p>Uaktywnij bsługę JavaScript.</p></noscript>

      <!-- blok tytułu strony -->
      <h1>{% block tytul_h1 %}{% endblock %}</h1>

      <!-- blok treści -->
      <div class="tresc">
        {% block tresc %}{% endblock %}
      </div>

    </div>

    <div class="col-sm-3 col-sm-offset-1">
      <div class="well">
        <h4>Przydatne linki</h4>
        <ul>
          {% block linki_ul %}{% endblock %}
        </ul>
      </div> <!--/well-->
    </div>

  </div> <!--/row -->
</div> <!--/container -->

<div class="container footer">
  <footer>
    <div class="row">
      <div class="col-sm-12 text-center">
        <div class="well">Django web framework – kurs błyskawiczny!<br>&copy; by Koduj z klasą 2017</div>
      </div>
    </div>
  </footer>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</body>
</html>

malybar/pizza/templates/pizza/index.html
{% extends "pizza/base.html" %}
{% block tytul_head %}
Aplikacja Mały Bar! wer1
{% endblock %}
{% block tytul_h1 %}Mały Bar{% endblock %}

{% block tresc %}

<p>{{ komunikat }}</p>
<a href ='kontakt'>kontakt</a>
<ul>
  {% if not user.is_authenticated %}
    <li><a href="{% url 'auth_login' %}">Zaloguj się</a></li>
    <li><a href="{% url 'registration_register' %}">Utwórz konto</a></li>

  {% else %}
    <li><a href="{% url 'pizza:lista' %}">lista pizz</a></li>
    <li><a href="{% url 'pizza:listas' %}">lista skladnikow</a></li>
    <li><a href="{% url 'auth_logout' %}">Wyloguj się</a></li>

  {% endif %}
</ul>

{% endblock %}

malybar/pizza/templates/pizza/kontakt.html
{% extends "pizza/base.html" %}
{% block tresc %}
<h1>Mały Bar</h1>
<p>{{ kontakt }}</p>
<p> 1111111111111</p>
{% endblock %}

malybar/pizza/templates/pizza/pizza_confirm_delete.html
{% extends "pizza/base.html" %}
{% block tresc %}

<h1>Usuwanie pizzy</h1>
<form action="." method="post">
  {% csrf_token %}
  <p>Czy na pewno chcesz usunąć pizzę:<br />"{{ object }}"?</p>
    <ol>Składniki:
    {% for s in skladniki %}
      <li>{{ s.nazwa }}</li>
    {% endfor %}
    </ol>
  <button type="submit">Usuń</button>
</form>
{% endblock %}

malybar/pizza/templates/pizza/pizza_detail.html
{% extends 'pizza/base.html' %}

{% block tytul_head %}
Pizza - info2
{% endblock %}

{% block tresc %}
<h2>{{object.nazwa}}</h2>

<table class="table table-striped">
<tr><td>Opis</td><td>{{ object.opis }}</td></tr>
<tr><td>Rozmiar</td><td>{{ object.rozmiar }}</td></tr>
<tr><td>Cena</td><td>{{ object.cena}}</td></tr>
<tr><td>Data</td><td>{{ object.data }}</td></tr>
<tr><td>Autor</td><td>{{ object.autor.username}}</td></tr>
</table>
    <ol>Składniki:
    {% for s in skladniki %}
      <li>{{ s.nazwa }} ({{s.czy_jarski}})</li>
    {% endfor %}
    </ol>
{% endblock %}

malybar/pizza/templates/pizza/pizza_form.html
{% extends "pizza/base.html" %}
{% block tresc %}
<h1>Dodaj pizzę</h1>

<form action="." method="post" id="pform">
    {% csrf_token %}
    {{ form.as_p }}

    <h3>Składniki:</h3>
    {{ skladniki.management_form }}
    {{ skladniki.non_form_errors }}
    {% for skl in skladniki %}
    {{ skl.id }}
        <div class="{{ skladniki.prefix }}">
            <span>{{ forloop.counter }})&nbsp;</span>       {{ skl.nazwa.errors }}
            {{ skl.jarski.errors }}
            {{ skl.nazwa.label_tag }} {{ skl.nazwa }}
            {{ skl.jarski.label_tag }} {{ skl.jarski }}
        </div>
    {% endfor %}
    <br /><input type="submit" value="Zapisz">
</form>
<h1>{{imie}}</h1>
{% endblock %}

malybar/pizza/templates/pizza/pizza_list.html
{% extends "pizza/base.html" %}
{% block tresc %}
<h1>Lista pizz ver2</h1>

<table class="table">
<tr><th>Lp.</th><th>Nazwa</th><th>Info</th><th>Operacje</th></tr>
{% for p in object_list %}
<tr>
    <td>{{ forloop.counter }}</td>
    <td>{{ p.nazwa }}</td>
    <td>{{ p.autor.username }} ({{ p.data }})</td>
    <td>
        {% if p.autor.username == user.username %}
            <a href="{% url 'pizza:edytuj' p.id %}">Edytuj</a> &bull;
            <a href="{% url 'pizza:usun' p.id %}">Usuń</a>
            <a href="{% url 'pizza:info' p.id %}">info</a>
        {% endif %}
    </td>
</tr>
{% endfor %}
</table>
{% endblock %}

malybar/pizza/templates/pizza/skladnik_list.html
{% extends "pizza/base.html" %}
{% block tresc %}
<h1>Lista skladnikow</h1>

<table class="table">
<tr><th>Lp.</th><th>Nazwa</th><th>Info</th><th>Operacje</th></tr>
{% for p in object_list %}
<tr>
    <td>{{ forloop.counter }}</td>
    <td>{{ p.nazwa }}</td>
    <td>{{ p.pizza.nazwa }}</td>
    <td>
        {% if p.autor.username == user.username %}
            <a href="#">Edytuj</a> &bull;
            <a href="#">Usuń</a>
        {% endif %}
    </td>
</tr>
{% endfor %}
</table>
{% endblock %}